package gui;

import java.io.IOException;

import controllers.GebruikerController;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Button;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;

public class DashboardSchermAdministratorController extends AnchorPane{
	@FXML
	private Button btnAfmelden;
	@FXML
	private Button btnKlantenBeheren;
	@FXML
	private Button btnWerknemersBeheren;

	private LoginSchermController parent;
	private GebruikerController gc;
	
	public DashboardSchermAdministratorController(LoginSchermController loginSchermController, GebruikerController gebruikerController) {
		this.parent= loginSchermController;
		this.gc = gebruikerController;
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("DashboardSchermAdministrator.fxml"));
			loader.setRoot(this);
			loader.setController(this);
			loader.load();
			
		} catch (IOException ex) {
			throw new RuntimeException(ex);
		}
	}
	// Event Listener on Button[#btnAfmelden].onAction
	@FXML
	public void btnAfmeldenOnAction(ActionEvent event) {
		Stage stage = (Stage) (getScene().getWindow());
		stage.setScene(this.parent.getScene());
	}
	// Event Listener on Button[#btnKlantenBeheren].onAction
	@FXML
	public void btnKlantenBeherenOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnWerknemersBeheren].onAction
	@FXML
	public void btnWerknemersBeherenOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
