package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import domein.controllers.AangemeldeGebruikerController;
import domein.controllers.AdministratorController;
import domein.models.Administrator;
import domein.models.Gebruiker;
import domein.models.GebruikerStatus;
import domein.models.SupportManager;
import domein.models.Medewerker;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.input.MouseEvent;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;
import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.control.TableColumn;

public class KlantenBeherenSchermController extends BorderPane implements Initializable{
	@FXML
	private Button btnKlantToevoegen;
	@FXML
	private Button btnKlantWijzigen;
	@FXML
	private Button btnTerug;
	@FXML
	private Button btnKlantDetails;
	
	@FXML
	private TableView<Gebruiker> tblView;
	@FXML
	private TableColumn<Gebruiker, String> colGebruikersnaam;
	@FXML
	private TableColumn<Gebruiker, String> colNaam;
	@FXML
	private TableColumn<Gebruiker, String> colVoornaam;
	@FXML
	private TableColumn<Gebruiker, String> colStatus;

	private DashboardSchermController parent;
	private AangemeldeGebruikerController ac;
	private Gebruiker selectedUser;

	public KlantenBeherenSchermController(DashboardSchermController dashboardSchermController, AangemeldeGebruikerController ac) {
		this.parent = dashboardSchermController;
		this.ac= ac;
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("KlantenBeherenScherm.fxml"));
			loader.setRoot(this);
			loader.setController(this);
			loader.load();
			
			btnKlantDetails.setDisable(true);

		} catch (IOException ex) {
			throw new RuntimeException(ex);
		}
	}

	// Event Listener on Button[#btnKlantToevoegen].onAction
	@FXML
	public void btnKlantToevoegenOnAction(ActionEvent event) {
		KlantToevoegenSchermController ktsc = new KlantToevoegenSchermController(this, ac);

		Scene scene = new Scene(ktsc);
		Stage stage = (Stage) this.getScene().getWindow();
		stage.setScene(scene);
		stage.show();
	}

	// Event Listener on Button[#btnKlantWijzigen].onAction
	@FXML
	public void btnKlantWijzigenOnAction(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#btnTerug].onAction
	@FXML
	public void btnTerugOnAction(ActionEvent event) {
		Stage stage = (Stage) (getScene().getWindow());
		stage.setScene(this.parent.getScene());
	}

	// Event Listener on Button[#btnKlantDetails].onAction
	@FXML
	public void btnKlantDetailsOnAction(ActionEvent event) {
		this.selectedUser= tblView.getSelectionModel().getSelectedItem();
		KlantDetailsSchermController werknemerDetailsSchermController = new KlantDetailsSchermController(this, this.selectedUser);

		Scene scene = new Scene(werknemerDetailsSchermController);
		Stage stage = (Stage) this.getScene().getWindow();
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on TableView[#tblView].onMouseClicked
	@FXML
	public void userClickedOnTable(MouseEvent event) {
        this.btnKlantDetails.setDisable(false);
    }

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		colGebruikersnaam.setCellValueFactory(new PropertyValueFactory<Gebruiker, String>("emailAdres"));
		colNaam.setCellValueFactory(new PropertyValueFactory<Gebruiker, String>("naam"));
		colVoornaam.setCellValueFactory(new PropertyValueFactory<Gebruiker, String>("voornaam"));
		colStatus.setCellValueFactory(new PropertyValueFactory<Gebruiker, String>("status"));
        tblView.setItems(ac.geefKlanten());
        
	}
}
