package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.layout.GridPane;

import java.io.IOException;
import java.time.LocalDate;
import java.util.Date;

import domein.controllers.AangemeldeGebruikerController;
import domein.models.GebruikerGegevens;
import domein.models.TicketStatus;
import javafx.collections.FXCollections;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.TextArea;

import javafx.scene.control.ChoiceBox;

public class TicketToevoegenSchermController extends GridPane {
	@FXML
	private Label lblTitel;
	@FXML
	private Button btnKlantAanmaken;
	@FXML
	private Label lblFout;
	@FXML
	private TextField txfTitel;
	@FXML
	private TextField txfKlantId;
	@FXML
	private Label lblStatus;
	@FXML
	private ChoiceBox<Integer> cboType;
	@FXML
	private Button btnBestandenToevoegen;
	@FXML
	private Label lblBijlage;
	@FXML
	private TextArea txaOmschrijving;
	@FXML
	private TextArea txaOpmerkingen;
	@FXML
	private ChoiceBox<GebruikerGegevens> cboTechnieker;
	@FXML
	private ChoiceBox cboStatus;

	private AangemeldeGebruikerController ac;

	public TicketToevoegenSchermController(TicketsBeherenSchermController ticketsBeherenSchermController,
			AangemeldeGebruikerController ac) {
		try {
			this.ac = ac;

			FXMLLoader loader = new FXMLLoader(getClass().getResource("TicketToevoegenScherm.fxml"));
			loader.setRoot(this);
			loader.setController(this);
			loader.load();

			cboStatus.setVisible(false);
			lblStatus.setVisible(false);
			
			cboType.setItems(FXCollections.observableArrayList(new Integer[] {1, 2, 3}));		
			cboTechnieker.setItems(ac.geefTechniekers());

		} catch (IOException ex) {
			throw new RuntimeException(ex);
		}
	}

	// Event Listener on Button[#btnKlantAanmaken].onAction
	@FXML
	public void btnKlantAanmakenOnAction(ActionEvent event) {

		try {
			if (!txfTitel.getText().isBlank()) {
				if (!txaOmschrijving.getText().isBlank()) {
					if (!txaOpmerkingen.getText().isBlank()) {
						if (cboType.getValue() != null) {
							if (!txfKlantId.getText().isBlank()) {
								if (cboTechnieker.getValue() != null) {
									ac.voegTicketToe(txfTitel.getText(), TicketStatus.Aangemaakt, LocalDate.now(),
											txaOmschrijving.getText(), txaOpmerkingen.getText(),
											Integer.parseInt(cboType.getValue().toString()), Integer.parseInt(txfKlantId.getText()),
											Integer.parseInt(cboTechnieker.getValue().toString()), "Geen bijlage");
									resetVelden();
									lblFout.setText("Ticket aanmaken gelukt!");
								} else
									lblFout.setText("Gelieve een technieker te selecteren.");
							} else
								lblFout.setText("Gelieve een klantId in te voeren.");
						} else
							lblFout.setText("Gelieve een tickettype te selecteren.");
					}
				} else
					lblFout.setText("Gelive een omschrijving in te vullen.");
			} else
				lblFout.setText("Gelieve een titel in te vullen");
		} catch (IllegalArgumentException e) {
			lblFout.setText(e.getMessage());
		}

	}
	private void resetVelden() {		

		txfTitel.clear();
		txaOmschrijving.clear();
		txaOpmerkingen.clear();
		cboType.setValue(null);
		txfKlantId.clear();
		cboTechnieker.setValue(null);
	}

	// Event Listener on Button[#btnBestandenToevoegen].onAction
	@FXML
	public void btnBestandenToevoegen(ActionEvent event) {
		// TODO Autogenerated
	}
}
