package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.layout.GridPane;

import java.io.IOException;

import domein.controllers.AangemeldeGebruikerController;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.TextArea;

import javafx.scene.control.ChoiceBox;

public class TicketToevoegenSchermController extends GridPane{
	@FXML
	private Label lblTitel;
	@FXML
	private Button btnKlantAanmaken;
	@FXML
	private Label lblFout;
	@FXML
	private TextField txfTitel;
	@FXML
	private TextField txfKlantId;
	@FXML
	private Label lblStatus;
	@FXML
	private ChoiceBox cboType;
	@FXML
	private Button btnBestandenToevoegen;
	@FXML
	private Label lblBijlage;
	@FXML
	private TextArea txaOmschrijving;
	@FXML
	private TextArea txaOpmerkingen;
	@FXML
	private ChoiceBox cboTechnieker;

	public TicketToevoegenSchermController(TicketsBeherenSchermController ticketsBeherenSchermController,
			AangemeldeGebruikerController ac) {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("TicketToevoegenScherm.fxml"));
			loader.setRoot(this);
			loader.setController(this);
			loader.load();
					
		} catch (IOException ex) {
			throw new RuntimeException(ex);
		}	}
	// Event Listener on Button[#btnKlantAanmaken].onAction
	@FXML
	public void btnKlantAanmakenOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnBestandenToevoegen].onAction
	@FXML
	public void btnBestandenToevoegen(ActionEvent event) {
		// TODO Autogenerated
	}
}
