package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import java.io.IOException;

import domein.controllers.AangemeldeGebruikerController;
import javafx.event.ActionEvent;

import javafx.scene.control.TableView;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;
import javafx.scene.control.TableColumn;

public class WerknemersBeherenSchermController extends BorderPane {
	@FXML
	private Button btnWerknemerToevoegen;
	@FXML
	private Button btnWerknemerWijzigen;
	@FXML
	private Button btnTerug;
	@FXML
	private TableView tblView;
	@FXML
	private TableColumn ColGebruikersnaam;
	@FXML
	private TableColumn ColNaam;
	@FXML
	private TableColumn ColVoornaam;
	@FXML
	private TableColumn ColRol;
	@FXML
	private TableColumn ColStatus;

	private DashboardSchermGebruikerController parent;

	private AangemeldeGebruikerController ac;

	public WerknemersBeherenSchermController(DashboardSchermGebruikerController dsgc,
			AangemeldeGebruikerController ac) {
		this.parent = dsgc;
		this.ac = ac;
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("WerknemersBeherenScherm.fxml"));
			loader.setRoot(this);
			loader.setController(this);
			loader.load();

		} catch (IOException ex) {
			throw new RuntimeException(ex);
		}
	}

	// Event Listener on Button[#btnWerknemerToevoegen].onAction
	@FXML
	public void btnWerknemerToevoegenOnAction(ActionEvent event) {
		WerknemerToevoegenSchermController wtsc = new WerknemerToevoegenSchermController(this);

		Scene scene = new Scene(wtsc);
		Stage stage = (Stage) this.getScene().getWindow();
		stage.setScene(scene);
		stage.show();
	}

	// Event Listener on Button[#btnWerknemerWijzigen].onAction
	@FXML
	public void btnWerknemerWijzigenOnAction(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#btnTerug].onAction
	@FXML
	public void btnTerugOnAction(ActionEvent event) {
		Stage stage = (Stage) (getScene().getWindow());
		stage.setScene(this.parent.getScene());
	}
}
