package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.control.Button;

import java.io.IOException;

import domein.controllers.AangemeldeGebruikerController;
import javafx.event.ActionEvent;

import javafx.scene.control.TableView;
import javafx.scene.layout.BorderPane;
import javafx.scene.control.TableColumn;

public class WerknemersBeherenSchermController extends BorderPane {
	@FXML
	private Button btnWerknemerToevoegen;
	@FXML
	private Button btnWerknemerWijzigen;
	@FXML
	private TableView tblView;
	@FXML
	private TableColumn ColGebruikersnaam;
	@FXML
	private TableColumn ColNaam;
	@FXML
	private TableColumn ColVoornaam;
	@FXML
	private TableColumn ColRol;
	@FXML
	private TableColumn ColStatus;

	private DashboardSchermGebruikerController parent;

	private AangemeldeGebruikerController ac;

	public WerknemersBeherenSchermController(DashboardSchermGebruikerController dsgc,
			AangemeldeGebruikerController ac) {
		this.parent = dsgc;
		this.ac = ac;
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("WerknemersBeherenScherm.fxml"));
			loader.setRoot(this);
			loader.setController(this);
			loader.load();

		} catch (IOException ex) {
			throw new RuntimeException(ex);
		}
	}
	// Event Listener on Button[#btnWerknemerToevoegen].onAction
	@FXML
	public void btnWerknemerToevoegenOnAction(ActionEvent event) {
		loadUi("GebruikerToevoegenScherm");
	}
	// Event Listener on Button[#btnWerknemerWijzigen].onAction
	@FXML
	public void btnWerknemerWijzigenOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	private void loadUi(String ui)
	{
		Parent root;
		try {
			root = FXMLLoader.load(getClass().getResource(ui+".fxml"));
		}catch(IOException ex)
		{
			throw new RuntimeException(ex);
		}
		this.setRight(root);
	}
}
